2025-09-10 20:48:34,160 - werkzeug - WARNING -  * Debugger is active!
2025-09-10 20:48:34,160 - werkzeug - INFO -  * Debugger PIN: 108-135-118
2025-09-10 20:48:49,941 - root - ERROR - Error occured in python script name [/media/shrav/New Volume/projects/ML_project/src/utils.py] line number [61] err message[[Errno 2] No such file or directory: 'artifacts\\model.pkl']
2025-09-10 20:48:49,941 - root - ERROR - Error occured in python script name [/media/shrav/New Volume/projects/ML_project/src/utils.py] line number [65] err message[Error occured in python script name [/media/shrav/New Volume/projects/ML_project/src/utils.py] line number [61] err message[[Errno 2] No such file or directory: 'artifacts\\model.pkl']]
2025-09-10 20:48:49,960 - werkzeug - INFO - 127.0.0.1 - - [10/Sep/2025 20:48:49] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
2025-09-10 20:48:49,979 - werkzeug - INFO - 127.0.0.1 - - [10/Sep/2025 20:48:49] "[36mGET /predictdata?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-09-10 20:48:49,979 - werkzeug - INFO - 127.0.0.1 - - [10/Sep/2025 20:48:49] "[36mGET /predictdata?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-09-10 20:48:49,991 - werkzeug - INFO - 127.0.0.1 - - [10/Sep/2025 20:48:49] "GET /predictdata?__debugger__=yes&cmd=resource&f=console.png&s=dbSkM9pVwJMPQV6oWWt0 HTTP/1.1" 200 -
2025-09-10 20:48:50,000 - werkzeug - INFO - 127.0.0.1 - - [10/Sep/2025 20:48:50] "[36mGET /predictdata?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-09-10 20:49:42,648 - werkzeug - INFO -  * Detected change in '/media/shrav/New Volume/projects/ML_project/app.py', reloading
